# Sets
#   TRILINOS_INCLUDE_DIR
#   TRILINOS_LIBRARIES
#   CF_HAVE_TRILINOS
#


SET_TRIAL_INCLUDE_PATH ("") # clear include search path
SET_TRIAL_LIBRARY_PATH ("") # clear library search path

ADD_TRIAL_INCLUDE_PATH( ${TRILINOS_HOME}/include )
ADD_TRIAL_INCLUDE_PATH( $ENV{TRILINOS_HOME}/include )

FIND_PATH( TRILINOS_INCLUDE_DIR Epetra_Vector.h ${TRIAL_INCLUDE_PATHS}  NO_DEFAULT_PATH )
FIND_PATH( TRILINOS_INCLUDE_DIR Epetra_Vector.h )

ADD_TRIAL_LIBRARY_PATH(${TRILINOS_HOME}/lib )
ADD_TRIAL_LIBRARY_PATH($ENV{TRILINOS_HOME}/lib )

FIND_LIBRARY(TRILINOS_TEUCHOS_LIB teuchos ${TRIAL_LIBRARY_PATHS}  NO_DEFAULT_PATH)
FIND_LIBRARY(TRILINOS_TEUCHOS_LIB teuchos )

FIND_LIBRARY(TRILINOS_THYRA_LIB thyracore ${TRIAL_LIBRARY_PATHS}  NO_DEFAULT_PATH)
FIND_LIBRARY(TRILINOS_THYRA_LIB thyracore )

FIND_LIBRARY(TRILINOS_THYRAEPETRA_LIB thyraepetra ${TRIAL_LIBRARY_PATHS}  NO_DEFAULT_PATH)
FIND_LIBRARY(TRILINOS_THYRAEPETRA_LIB thyraepetra )

FIND_LIBRARY(TRILINOS_THYRAEPETRAEXT_LIB thyraepetraext ${TRIAL_LIBRARY_PATHS}  NO_DEFAULT_PATH)
FIND_LIBRARY(TRILINOS_THYRAEPETRAEXT_LIB thyraepetraext )

FIND_LIBRARY(TRILINOS_STRATIMIKOS_LIB stratimikos ${TRIAL_LIBRARY_PATHS}  NO_DEFAULT_PATH)
FIND_LIBRARY(TRILINOS_STRATIMIKOS_LIB stratimikos )

FIND_LIBRARY(TRILINOS_STRATIMIKOSAMESOS_LIB stratimikosamesos ${TRIAL_LIBRARY_PATHS}  NO_DEFAULT_PATH)
FIND_LIBRARY(TRILINOS_STRATIMIKOSAMESOS_LIB stratimikosamesos )

FIND_LIBRARY(TRILINOS_STRATIMIKOSAZTECOO_LIB stratimikosaztecoo ${TRIAL_LIBRARY_PATHS}  NO_DEFAULT_PATH)
FIND_LIBRARY(TRILINOS_STRATIMIKOSAZTECOO_LIB stratimikosaztecoo )

FIND_LIBRARY(TRILINOS_STRATIMIKOSBELOS_LIB stratimikosbelos ${TRIAL_LIBRARY_PATHS}  NO_DEFAULT_PATH)
FIND_LIBRARY(TRILINOS_STRATIMIKOSBELOS_LIB stratimikosbelos )

FIND_LIBRARY(TRILINOS_STRATIMIKOSIFPACK_LIB stratimikosifpack ${TRIAL_LIBRARY_PATHS}  NO_DEFAULT_PATH)
FIND_LIBRARY(TRILINOS_STRATIMIKOSIFPACK_LIB stratimikosifpack )

FIND_LIBRARY(TRILINOS_STRATIMIKOSML_LIB stratimikosml ${TRIAL_LIBRARY_PATHS}  NO_DEFAULT_PATH)
FIND_LIBRARY(TRILINOS_STRATIMIKOSML_LIB stratimikosml )

FIND_LIBRARY(TRILINOS_EPETRA_LIB epetra ${TRIAL_LIBRARY_PATHS}  NO_DEFAULT_PATH)
FIND_LIBRARY(TRILINOS_EPETRA_LIB epetra )

FIND_LIBRARY(TRILINOS_AZTECOO_LIB aztecoo ${TRIAL_LIBRARY_PATHS}  NO_DEFAULT_PATH)
FIND_LIBRARY(TRILINOS_AZTECOO_LIB aztecoo )

FIND_LIBRARY(TRILINOS_EPETRAEXT_LIB epetraext ${TRIAL_LIBRARY_PATHS}  NO_DEFAULT_PATH)
FIND_LIBRARY(TRILINOS_EPETRAEXT_LIB epetraext )

FIND_LIBRARY(TRILINOS_IFPACK_LIB ifpack ${TRIAL_LIBRARY_PATHS}  NO_DEFAULT_PATH)
FIND_LIBRARY(TRILINOS_IFPACK_LIB ifpack )

FIND_LIBRARY(TRILINOS_ML_LIB ml ${TRIAL_LIBRARY_PATHS}  NO_DEFAULT_PATH)
FIND_LIBRARY(TRILINOS_ML_LIB ml )

FIND_LIBRARY(TRILINOS_AMESOS_LIB amesos ${TRIAL_LIBRARY_PATHS}  NO_DEFAULT_PATH)
FIND_LIBRARY(TRILINOS_AMESOS_LIB amesos )

FIND_LIBRARY(TRILINOS_BELOS_LIB belos ${TRIAL_LIBRARY_PATHS}  NO_DEFAULT_PATH)
FIND_LIBRARY(TRILINOS_BELOS_LIB belos )

FIND_LIBRARY(TRILINOS_BELOSEPETRA_LIB belosepetra ${TRIAL_LIBRARY_PATHS}  NO_DEFAULT_PATH)
FIND_LIBRARY(TRILINOS_BELOSEPETRA_LIB belosepetra )

FIND_LIBRARY(TRILINOS_MEROS_LIB meros ${TRIAL_LIBRARY_PATHS}  NO_DEFAULT_PATH)
FIND_LIBRARY(TRILINOS_MEROS_LIB meros )

LIST ( APPEND TRILINOS_LIBRARIES 
  ${TRILINOS_TEUCHOS_LIB}
  ${TRILINOS_EPETRA_LIB}
  ${TRILINOS_AZTECOO_LIB}
  ${TRILINOS_EPETRAEXT_LIB}
  ${TRILINOS_IFPACK_LIB}
  ${TRILINOS_ML_LIB}
  ${TRILINOS_THYRA_LIB}
  ${TRILINOS_THYRAEPETRA_LIB}
  ${TRILINOS_THYRAEPETRAEXT_LIB}
  ${TRILINOS_STRATIMIKOS_LIB}
  ${TRILINOS_STRATIMIKOSAMESOS_LIB}
  ${TRILINOS_STRATIMIKOSAZTECOO_LIB}
  ${TRILINOS_STRATIMIKOSBELOS_LIB}
  ${TRILINOS_STRATIMIKOSIFPACK_LIB}
  ${TRILINOS_STRATIMIKOSML_LIB}
  ${TRILINOS_AMESOS_LIB}
  ${TRILINOS_BELOS_LIB}
  ${TRILINOS_BELOSEPETRA_LIB}
#  ${TRILINOS_MEROS_LIB} 
)

IF ( TRILINOS_INCLUDE_DIR AND TRILINOS_LIBRARIES)
  
  IF ( CF_HAVE_BLASLAPACK )
    
    SET ( CF_HAVE_TRILINOS 1 CACHE BOOL "Found Trilinos library" )
  
  ELSE()
    
    LOG ( "Trilinos available but lapack or blas not found." )
    SET ( CF_HAVE_TRILINOS 0 CACHE BOOL "Not using Trilinos library because Lapack was not found" )
  
  ENDIF ()

ELSE(TRILINOS_INCLUDE_DIR AND TRILINOS_LIBRARIES)

  SET(CF_HAVE_TRILINOS 0 CACHE BOOL "Not fount Trilinos library")

ENDIF()

MARK_AS_ADVANCED (
  TRILINOS_INCLUDE_DIR
  TRILINOS_LIBRARIES
  CF_HAVE_TRILINOS
  TRILINOS_TEUCHOS_LIB
  TRILINOS_EPETRA_LIB
  TRILINOS_AZTECOO_LIB
  TRILINOS_EPETRAEXT_LIB
  TRILINOS_IFPACK_LIB
  TRILINOS_ML_LIB
  TRILINOS_THYRA_LIB
  TRILINOS_THYRAEPETRA_LIB
  TRILINOS_THYRAEPETRAEXT_LIB
  TRILINOS_STRATIMIKOS_LIB
  TRILINOS_STRATIMIKOSAMESOS_LIB
  TRILINOS_STRATIMIKOSAZTECOO_LIB
  TRILINOS_STRATIMIKOSBELOS_LIB
  TRILINOS_STRATIMIKOSIFPACK_LIB
  TRILINOS_STRATIMIKOSML_LIB
  TRILINOS_AMESOS_LIB
  TRILINOS_BELOS_LIB
  TRILINOS_BELOSEPETRA_LIB
  TRILINOS_MEROS_LIB
)

LOG ( "CF_HAVE_TRILINOS: [${CF_HAVE_TRILINOS}]" )
IF (CF_HAVE_TRILINOS)
   LOG ( "  TRILINOS_INCLUDE_DIR: [${TRILINOS_INCLUDE_DIR}]" )
   LOG ( "  TRILINOS_LIBRARIES:   [${TRILINOS_LIBRARIES}]" )
ENDIF ()
