# Needs environmental variables
#   SAMG_HOME
#   SAMG_OPTIONS
# Sets
#   SAMG_INCLUDE_DIR
#   SAMG_LIBRARY
#   CF_HAVE_SAMG

ADD_TRIAL_INCLUDE_PATH( "${SAMG_HOME}" )
ADD_TRIAL_LIBRARY_PATH( "${SAMG_HOME}" )

FIND_PATH(SAMG_INCLUDE_DIR samg.h ${TRIAL_INCLUDE_PATHS} NO_DEFAULT_PATH)
FIND_PATH(SAMG_INCLUDE_DIR samg.h)

# for samgp
FIND_LIBRARY(SAMG_K1 amg    ${TRIAL_LIBRARY_PATHS} NO_DEFAULT_PATH)
FIND_LIBRARY(SAMG_K2 ifcore ${TRIAL_LIBRARY_PATHS} NO_DEFAULT_PATH)
FIND_LIBRARY(SAMG_K3 imf    ${TRIAL_LIBRARY_PATHS} NO_DEFAULT_PATH)

MARK_AS_ADVANCED ( SAMG_K1 SAMG_K2 SAMG_K3 )

## no mpi
#FIND_LIBRARY(SAMG_LIBRARY mpidummy ${TRIAL_LIBRARY_PATHS} NO_DEFAULT_PATH)

## for samg
#FIND_LIBRARY(SAMG_LIBRARY amg      ${TRIAL_LIBRARY_PATHS} NO_DEFAULT_PATH)
#FIND_LIBRARY(SAMG_LIBRARY ifport   ${TRIAL_LIBRARY_PATHS} NO_DEFAULT_PATH)
#FIND_LIBRARY(SAMG_LIBRARY ifcoremt ${TRIAL_LIBRARY_PATHS} NO_DEFAULT_PATH)
#FIND_LIBRARY(SAMG_LIBRARY imf      ${TRIAL_LIBRARY_PATHS} NO_DEFAULT_PATH)
#FIND_LIBRARY(SAMG_LIBRARY guide    ${TRIAL_LIBRARY_PATHS} NO_DEFAULT_PATH)
#FIND_LIBRARY(SAMG_LIBRARY cxaguard ${TRIAL_LIBRARY_PATHS} NO_DEFAULT_PATH)
#FIND_LIBRARY(SAMG_LIBRARY pthread  ${TRIAL_LIBRARY_PATHS} NO_DEFAULT_PATH)

IF(SAMG_INCLUDE_DIR AND SAMG_K1 AND SAMG_K2 AND SAMG_K3)
  SET(SAMG_LIBRARY ${SAMG_K1} ${SAMG_K2} ${SAMG_K3})
  SET(CF_HAVE_SAMG 1)
ELSE()
  SET(CF_HAVE_SAMG 0)
ENDIF()

MARK_AS_ADVANCED (
  SAMG_INCLUDE_DIR
  SAMG_LIBRARY
  SAMG_OPTIONS
  CF_HAVE_SAMG
)

LOG ( "CF_HAVE_SAMG: [${CF_HAVE_SAMG}]" )
IF(CF_HAVE_SAMG)
  LOGFILE ( "  SAMG_INCLUDE_DIR: [${SAMG_INCLUDE_DIR}]" )
  LOGFILE ( "  SAMG_LIBRARY:     [${SAMG_LIBRARY}]" )
  LOGFILE ( "  SAMG_OPTIONS:     [${SAMG_OPTIONS}]" )
ENDIF(CF_HAVE_SAMG)

