#
# this module look for PARMETIS (http://hdf.ncsa.uiuc.edu) support
# it will define the following values
#
# PARMETIS_INCLUDE_DIR  = where parmetis.h can be found
# PARMETIS_LIBRARY      = the library to link against (parmetis etc)
# CF_HAVE_PARMETIS        = set to true after finding the library
#

OPTION ( CF_SKIP_PARMETIS "Skip search for Parmetis library" OFF )

# dont search for parmetis without MPI
IF ( NOT CF_SKIP_PARMETIS OR NOT CF_HAVE_MPI )

  SET_TRIAL_INCLUDE_PATH ("") # clear include search path
  SET_TRIAL_LIBRARY_PATH ("") # clear library search path

  ADD_TRIAL_INCLUDE_PATH( ${PARMETIS_HOME}/include )
  ADD_TRIAL_INCLUDE_PATH( $ENV{PARMETIS_HOME}/include )

  FIND_PATH(PARMETIS_INCLUDE_DIR parmetis.h  ${TRIAL_INCLUDE_PATHS}  NO_DEFAULT_PATH)
  
  IF ( NOT PARMETIS_INCLUDE_DIR )
    FIND_PATH(PARMETIS_INCLUDE_DIR parmetis.h )
  ENDIF()

  ADD_TRIAL_LIBRARY_PATH( ${PARMETIS_HOME}/lib )
  ADD_TRIAL_LIBRARY_PATH( $ENV{PARMETIS_HOME}/lib )

  FIND_LIBRARY(PARMETIS_LIB_PARMETIS parmetis ${TRIAL_LIBRARY_PATHS} NO_DEFAULT_PATH)

  IF ( NOT PARMETIS_LIB_PARMETIS )
    FIND_LIBRARY(PARMETIS_LIB_PARMETIS parmetis )
  ENDIF() 

 FIND_LIBRARY(PARMETIS_LIB_METIS metis ${TRIAL_LIBRARY_PATHS} NO_DEFAULT_PATH)
  
 IF ( NOT PARMETIS_LIB_METIS )
    FIND_LIBRARY(PARMETIS_LIB_METIS metis )
 ENDIF()

 SET ( PARMETIS_LIBRARIES ${PARMETIS_LIB_PARMETIS} ${PARMETIS_LIB_METIS} )
 
  IF(PARMETIS_INCLUDE_DIR AND PARMETIS_LIBRARIES)
    SET(CF_HAVE_PARMETIS 1)
  ELSE()
    SET(CF_HAVE_PARMETIS 0)
  ENDIF()

ELSE()
    SET(CF_HAVE_PARMETIS 0)
ENDIF()

MARK_AS_ADVANCED(
  PARMETIS_INCLUDE_DIR
  PARMETIS_LIB_PARMETIS
  PARMETIS_LIB_METIS
  PARMETIS_LIBRARIES
  CF_HAVE_PARMETIS
)

LOG ( "CF_HAVE_PARMETIS: [${CF_HAVE_PARMETIS}]" )
IF(CF_HAVE_PARMETIS)
  LOG ( "  PARMETIS_INCLUDE_DIR: [${PARMETIS_INCLUDE_DIR}]" )
  LOG ( "  PARMETIS_LIBRARIES:   [${PARMETIS_LIBRARIES}]" )
ENDIF(CF_HAVE_PARMETIS)
